FROM jitsi/jvb:stable-9584

# Remove old libraries to avoid classpath conflicts
RUN rm -rf /usr/share/jitsi-videobridge/lib/*

# Copy the locally built multitrack-enabled videobridge and all its dependencies
COPY docker/jvb/jitsi-videobridge.jar /usr/share/jitsi-videobridge/jitsi-videobridge.jar
COPY docker/jvb/lib/ /usr/share/jitsi-videobridge/lib/
